coverage:
  status:
    project:
      default:
        target: auto
        paths:
          - "include/behaviortree_cpp/**"
          - "src/**"

flags:
  unittests:
    paths:
      - "include/behaviortree_cpp/**"
      - "src/**"

ignore:
  - "3rdparty/**"
  - "examples/**"
  - "include/**/contrib/**"
  - "sample_nodes/**"
  - "tests/**"
  - "tools/**"
