coverage:
  status:
    project:
      default:
        target: auto

ignore:
  - "3rdparty/**/*"
  - "examples/**/*"
  - "include/**/contrib/**/*"
  - "sample_nodes/**/*"
  - "tests/**/*"
  - "tools/**/*"
