name: Website
permissions:
  contents: write

on:
  push:
    branches: '**'
  pull_request:

jobs:
  website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install asciidoctor
      run: sudo gem install asciidoctor pygments.rb
    - name: Install hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DLEXY_BUILD_DOCS=ON -DLEXY_BUILD_EXAMPLES=OFF -DLEXY_BUILD_TESTS=OFF
    - name: Build docs
      working-directory: build/
      run: cmake --build . --target lexy_docs

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/public/

