---
header: "lexy/dsl/peek.hpp"
entities:
  "lexy::dsl::peek": peek
  "lexy::dsl::peek_not": peek_not
---
:toc: left

[.lead]
The `peek` and `peek_not` branch rules.

[#peek]
== Branch rule `lexy::dsl::peek`

{{% interface %}}
----
namespace lexy
{
    struct peek_failure {};
}

namespace lexy::dsl
{
    struct _peek_ // models _branch-rule_
    {
        template <typename Tag>
        static constexpr _peek_ error;
    };

    constexpr _peek_ peek(_rule_ auto rule);
}
----

[.lead]
`peek` is a {{% branch-rule %}} that checks if `rule` matches without consuming anything.

Parsing::
  Tries to match `rule` in a new context.
  If that succeeds, the branch is taken without consuming anything.
  Otherwise, it raises an error.
Branch parsing::
  Same as parsing, but backtracks instead of raising an error.
Errors::
  A generic error with the specified `Tag` or `lexy::peek_failure` at the position where it started to match rule.
  It then recovers without consuming additional input.
Values::
  None.

{{% playground-example peek "Parse an optional number" %}}

NOTE: Automatic {{% docref whitespace %}} skipping is disabled while parsing `rule`.

WARNING: `rule` does not have access to any context variables created by the context-sensitive parsing facilities and it can't use recursion.

CAUTION: This rule requires backtracking, which can slow down parsing.

[#peek_not]
== Branch rule `lexy::dsl::peek_not`

{{% interface %}}
----
namespace lexy
{
    struct unexpected {};
}

namespace lexy::dsl
{
    struct _peek_not_ // models _branch-rule_
    {
        template <typename Tag>
        static constexpr _peek_not_ error;
    };

    constexpr _peek_not_ peek_not(_rule_ auto rule);
}
----

[.lead]
`peek_not` is a {{% branch-rule %}} that checks if `rule` does not match without consuming anything.

Parsing::
  Tries to match `rule` in a new context.
  If that does not succeed, the branch is taken without consuming anything.
  Otherwise, it raises an error.
Branch parsing::
  Same as parsing, but backtracks instead of raising an error.
Errors::
  A generic error with the specified `Tag` or `lexy::unexpected` covering everything `rule` would have consumed.
  It then recovers without having consumed any input.
Values::
  None.

{{% playground-example peek_not "Explicitly prohibit trailing spaces" %}}

NOTE: Automatic {{% docref whitespace %}} skipping is disabled while parsing `rule`.

WARNING: `rule` does not have access to any context variables created by the context-sensitive parsing facilities and it can't use recursion.

CAUTION: This rule requires backtracking, which can slow down parsing.

