---
header: "lexy/dsl/production.hpp"
entities:
  "lexy::dsl::inline_": inline_
  "lexy::dsl::p": p
  "lexy::dsl::recurse": recurse
  "lexy::dsl::recurse_branch": recurse
---
:toc: left

[.lead]
The `inline_`, `p`, and `recurse` rules.

[#inline_]
== Rule `lexy::dsl::inline_`

{{% interface %}}
----
namespace lexy::dsl
{
    template <_production_ P>
    constexpr _rule_ auto inline_;

    template <_production_ P>
      requires _token-rule_<production_rule<P>>
    constexpr _token-rule_ auto inline_;

    template <_production_ P>
      requires _branch-rule_<production_rule<P>>
    constexpr _branch-rule_ auto inline_;
}
----

[.lead]
`inline_` is a rule that parses the rule of production `P` as part of the current production.

Requires::
  `P` is a complete type, i.e. `p` cannot be used for recursion.
Matching::
  Matches `P::rule`.
(Branch) Parsing::
  Parses `P::rule`.
Errors::
  All errors raised by `P::rule`.
  The rule then fails if `P::rule` has failed.
Values::
  All values produced by `P::rule`.

{{% playground-example inline "Parse a child production inline" %}}

TIP: Use `inline_` when you need to parse a production as part of the whitespace rule.

[#p]
== Rule `lexy::dsl::p`

{{% interface %}}
----
namespace lexy::dsl
{
    template <_production_ P>
    constexpr _rule_ auto p;

    template <_production_ P>
      requires _branch-rule_<production_rule<P>> && !_defines-whitespace_<P>`
    constexpr _branch-rule_ auto p;
}
----

[.lead]
`p` is a rule that parses the production `P`.

Requires::
  `P` is a complete type, i.e. `p` cannot be used for recursion.
(Branch) Parsing::
  Parses `P::rule` in a new context for `P`, potentially after skipping initial {{% docref "whitespace" %}} if `P::whitespace` has been defined.
Errors::
  All errors raised by parsing `P::rule`, but forwarded to the new context for `P`.
  The rule fails if `P::rule` has failed.
Values::
  All values produced by `P::rule` are forwarded to the new context, e.g. to `P::value`.
  The final value of the context is produced as the single value for `p`.
Parse tree::
  * If `P` inherits from {{% docref "lexy::transparent_production" %}}, the nodes generated by `P::rule` are added to the parse tree as if they were added by `p` itself.
  * Otherwise, it creates a single production node for `P`.
    Its children are all the nodes generated by `P::rule`.

{{% playground-example default "Parse a child production" %}}

{{% playground-example choice_production "Productions with branches" %}}

NOTE: The `p` rule cannot handle direct or indirect recursion, as `P` must be a complete type.

CAUTION: While parsing `P::rule`, the {{% docref "whitespace" "current whitespace rule" %}} can be different.
If whitespace parsing has been disabled using {{% docref "lexy::dsl::no_whitespace" %}},
it is temporarily re-enabled while parsing `P::rule`.
If whitespace parsing has been disabled because the current production inherits from {{% docref "lexy::token_production" %}},
it is still disabled, unless the current production explicitly defines a new whitespace rule.

[#recurse]
== Rule `lexy::dsl::recurse`

{{% interface %}}
----
namespace lexy
{
    struct max_recursion_depth_exceeded {};
}

namespace lexy::dsl
{
    struct _recurse_ // models _rule_ or _branch-rule_
    {
        template <typename Tag>
        static constexpr _recurse_ max_depth_error;
    };

    template <_production_ P>
    constexpr _recurse_ auto recurse;        // _rule_
    template <_production_ P>
    constexpr _recurse_ auto recurse_branch; // _branch-rule_
}
----

[.lead]
`recurse` is a rule that parses the production `P` but supports recursion.

It behaves similar to the `p` rule, but `P` does not need to a be a complete type, which allows recursion.
For the same reason, `recurse<P>` is never a branch rule: it can't know whether `P` is a branch.
Use `recurse_branch<P>` if you know that `P` is a branch; it will cause a delayed `static_assert` if it isn't.

Parsing::
  Checks whether the current depth of recursive production call exceeds the maximum parse depth,
  which is determined by {{% docref "lexy::max_recursion_depth" %}}.
  Fails, if that is the case.
  Otherwise, parses `p<P>`, i.e. the production `P`.
Branch parsing::
  Branch parses `p<P>`, i.e. the production `P`.
  The recursive depth check is done after the branch condition has matched.
  It will not backtrack if the condition matches but the depth is exceeded.
Errors::
  * A generic error with the specified `Tag` or `lexy::max_recursion_depth_exceeded` if the recursive depth is exceeded,
    at the position where it would have started to match the production.
    It then fails without recovering.
  * All errors raised by parsing `p<P>`.

{{% playground-example recurse "Parse a parenthesized expression" %}}

{{% playground-example recurse_limit "Parse a parenthesized expression with a recursion limit" %}}

WARNING: Left recursion will create a max recursion error.
Use {{% docref "lexy::dsl::loop" %}} or {{% docref "lexy::dsl::list"%}} instead.

NOTE: The recursion depth only counts productions parsed by `recurse`; intermediate productions parsed using `p` are ignored.
In particular, the nesting level of `p` rules, which is statically determined by the grammar and not by the input, is allowed to exceed the maximum recursion depth.

