name: colcon ament Ubuntu

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    container: osrf/ros:${{matrix.ros_distro}}-desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        ros_distro: [humble, rolling]
    steps:
    - uses: actions/checkout@v2

    - name: Install binary dependencies with rosdep
      id: rosdep
      run: |
        apt update
        rosdep update
        source /opt/ros/${{matrix.ros_distro}}/setup.bash
        rosdep install --from-paths src --ignore-src -y
      shell: bash

    - name: Build with colcon
      id: colcon-build
      run: |
        source /opt/ros/${{matrix.ros_distro}}/setup.bash
        colcon build
      shell: bash

    - name: Test with colcon
      id: colcon-test
      run: |
        source /opt/ros/${{matrix.ros_distro}}/setup.bash
        colcon test
        colcon test-result --all --verbose
      shell: bash

    - name: Test consuming with ament_target_dependencies
      run: |
        source /opt/ros/${{matrix.ros_distro}}/setup.bash
        # This sets the variable AMENT_PREFIX_PATH
        source install/setup.bash
        cd tests/export/ament_target_deps
        colcon build

    - name: Test consuming with target_link_libraries
      run: |
        source /opt/ros/${{matrix.ros_distro}}/setup.bash
        # This sets the variable AMENT_PREFIX_PATH
        source install/setup.bash
        cd tests/export/target_link_libs
        colcon build
